folder_in: /home/user/tst
folder_out: /home/user/out
folder_ext: /home/user/folder1
folder_ext2: /home/user/folder2
folder_extract: /home/user/folder_extract
count: 5
bs: 1M
type: zip
stat_file: /home/user/stat.txt